name: Build and deploy Vite React frontend to Azure Web App - WHS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.5

      - name: Install dependencies (frontend)
        run: cd frontend && bun install

      - name: Build frontend (Vite + React + TS)
        run: cd frontend && bun run build

      - name: Show build output
        run: ls -lh frontend/dist

      - name: Zip artifact for deployment
        run: cd frontend/dist && zip -r ../../../release.zip .

      - name: List workspace before upload
        run: ls -lh .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: bun-frontend
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: List workspace before download
        run: ls -lh .

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bun-frontend

      - name: List workspace after download
        run: ls -lh .

      - name: Extract artifact to folder
        run: |
          mkdir deploy
          unzip -o release.zip -d deploy

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_59528D59F9D14B3AB460E810E3FFBB34 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_78D16F13E55C4397B5E7C0F61A97EA5A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC6A68BBD38B49AD8E581CF39361EDB3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WHS'
          slot-name: 'Production'
          package: './deploy'