name: Build and deploy Frontend (Bun) to Azure Web App - WHSrepresentaciones

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies and build (Bun)
        working-directory: ./frontend
        run: |
          bun install
          bun run build

      - name: Zip build artifact
        working-directory: ./frontend
        run: zip -r ../frontend-build.zip ./dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend-build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: frontend-build

      - name: Unzip artifact for deployment
        run: unzip frontend-build.zip -d site

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3C8E2D1144E04F34949DB2EB9790153A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7A5B264E37D94E718A664998D0BF0301 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9326E325A7AD454BB3F2708EC8A0545B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WHSrepresentaciones'
          slot-name: 'Production'
          package: ./site