name: Build and deploy Bun frontend to Azure Web App - WHSrepresentaciones

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd frontend && bun install

      - name: Build frontend
        run: cd frontend && bun run build

      - name: Zip artifact for deployment
        run: cd frontend && zip -r ../release.zip dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: bun-frontend
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bun-frontend

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WHSrepresentaciones'
          slot-name: 'Production'
          package: dist
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}